version: '3.7'
services:
  web:
    build: .
    # command: ["flask", "--app", "web/app", "run"]s
    command: ["gunicorn", "-w", "4", "web.app:app", "-b", "0.0.0.0:5000"]

  wetty_container:
      build: .
      depends_on:
        - web
      command: ["wetty", "--host", "0.0.0.0","--base", "/terminal", "--ssh-host", "web", "--ssh-port", "22","--allow-iframe", "-c", "bash", "-c", "'cd ebash; python3 ebash.py; exit;'"]

  nginx:
    build: .
    ports:
      - 4065:80
    depends_on:
      - web
      - wetty_container
    command: ["nginx", "-g", "daemon off;"]
